[licenses]
unlicensed = "deny"
copyleft = "deny"
default = "deny"
unused-allowed-license = "allow"
allow = [
    "0BSD",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSD-4-Clause",
    "CC0-1.0",
    "ISC",
    "MIT-0",
    "MIT",
    "MS-PL",
    "Unicode-DFS-2016",
    "Unlicense",
    "Zlib",
]

[[licenses.clarify]]
name = "databake-derive"
expression = "Unicode-DFS-2016"
license-files = [{ path = "LICENSE", hash = 0xbbcfaf3d }]

[[licenses.exceptions]]
name = "wasmparser"
allow = ["Apache-2.0 WITH LLVM-exception"]

[[licenses.exceptions]]
name = "target-lexicon"
allow = ["Apache-2.0 WITH LLVM-exception"]

[[licenses.exceptions]]
name = "dynasmrt"
allow = ["MPL-2.0"]

[[licenses.exceptions]]
name = "dynasm"
allow = ["MPL-2.0"]

[[licenses.exceptions]]
name = "generational-arena"
allow = ["MPL-2.0"]

[advisories]
ignore = ["RUSTSEC-2020-0056", "RUSTSEC-2020-0071"]
