name: Benchmarking

on:
  workflow_dispatch:

jobs:
  benchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    strategy:
      matrix:
        feature-sets:
          - []
          - [white-spaces]
          - [literals]
          - [literals, comments]
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Cargo cache
        uses: ./.github/actions/cargo-cache
        with:
          key: ${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust (nightly)
        uses: dtolnay/rust-toolchain@7c8d7d138f5c09cef361f8214cf96882cd029cdb # nightly
        with:
          toolchain: nightly
      - name: Run benchmark
        run: cargo bench --locked --no-default-features ${{ toJSON(matrix.feature-sets) != '[]' && format('--features {0}', join(matrix.feature-sets, ',')) || '' }}
