name: Benchmarking

on:
  workflow_dispatch:

jobs:
  benchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature-sets:
          - []
          - [white-spaces]
          - [literals]
          - [literals, comments]
    steps:
      - name: Check out repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Set up cache
        uses: actions/cache@87396fe6b4d327202df854ff5b3e0a4ea3d77ac6
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain update nightly
          rustup default nightly
      - name: Run benchmark
        run: cargo bench --locked --no-default-features ${{ toJSON(matrix.feature-sets) != '[]' && format('--features {0}', join(matrix.feature-sets, ',')) || '' }}
