name: Continuous integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
      - name: Set up Rust
        run: rustup default nightly
      - name: Install development tools
        uses: taiki-e/install-action@c0f0193890b634ca9905af48b8a11de78b7e18a5
        with:
          tool: cargo-deny@0.16.3, cargo-udeps@0.1.52, cargo-hack@0.6.33
      - name: Install Rust linters
        run: rustup component add clippy rustfmt
      - name: Run checks
        run: |
          cargo fmt --check --all
          cargo hack --feature-powerset --skip nightly check --locked --workspace
          cargo hack --feature-powerset --skip nightly clippy --locked --workspace -- -D warnings
          cargo deny check
          cargo udeps --locked --workspace
  tests:
    name: Test on ${{ matrix.os.name }} (${{ matrix.channel }})
    runs-on: ${{ matrix.os.value }}
    strategy:
      matrix:
        os:
          - name: Linux
            value: ubuntu-latest
          - name: Windows
            value: windows-latest
          - name: macOS
            value: macos-latest
        channel:
          - stable
          - beta
          - nightly
    steps:
      - name: Check out repository
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
      - name: Set up Rust
        run: rustup default ${{ matrix.channel }}
      - name: Install development tools
        uses: taiki-e/install-action@c0f0193890b634ca9905af48b8a11de78b7e18a5
        with:
          tool: cargo-hack@0.6.33
      - name: Run tests
        run: cargo hack --feature-powerset --skip nightly test --locked
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
      - name: Set up Rust
        run: rustup default nightly
      - name: Install development tools
        uses: taiki-e/install-action@c0f0193890b634ca9905af48b8a11de78b7e18a5
        with:
          tool: cargo-llvm-cov@0.6.14, cargo-hack@0.6.33
      - name: Create directories
        run: mkdir -p target/llvm-cov/lcov
      - name: Generate code coverage
        run: |
          cargo hack --feature-powerset --skip nightly llvm-cov --no-report --branch --locked
          cargo llvm-cov report --fail-under-lines 85 --lcov --output-path target/llvm-cov/lcov/${{ github.event.repository.name }}.info
      - name: Upload code coverage
        uses: romeovs/lcov-reporter-action@25674467b99fc58cc7706dc246d9647a94b5ba8f
        if: github.event_name == 'pull_request'
        with:
          lcov-file: target/llvm-cov/lcov/${{ github.event.repository.name }}.info
          delete-old-comments: true
  success:
    name: Success
    needs: [checks, tests, coverage]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check jobs
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
